name: mirage_masquerade
description: "Mirage Masquerade - synchronise three parallel theatres of illusion."
publish_to: 'none'
version: 1.0.2+15

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.5
  audioplayers: ^6.1.0
  webview_flutter: ^4.14.1
  webview_flutter_wkwebview: ^3.26.0
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  flutter_local_notifications: ^18.0.1
  appsflyer_sdk: ^6.18.0
  app_tracking_transparency: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/obj/
    - assets/img/fx/
    - assets/img/ui/
    - assets/img/bg/
    - assets/img/screen/
    - assets/sfx/
